#include "GDITypes.h"
#include <QMap>

#define DECL_ROP3(x)   {GDI_##x, #x}
QMap<uint8_t, QString> ROP3_TABLE = {
    DECL_ROP3(SRCCOPY),
    DECL_ROP3(SRCPAINT),
    DECL_ROP3(SRCAND),
    DECL_ROP3(SRCINVERT),
    DECL_ROP3(SRCERASE),
    DECL_ROP3(NOTSRCCOPY),
    DECL_ROP3(NOTSRCERASE),
    DECL_ROP3(MERGECOPY),
    DECL_ROP3(MERGEPAINT),
    DECL_ROP3(PATCOPY),
    DECL_ROP3(PATPAINT),
    DECL_ROP3(PATINVERT),
    DECL_ROP3(DSTINVERT),
    DECL_ROP3(BLACKNESS),
    DECL_ROP3(WHITENESS),

    DECL_ROP3(DSPDxax),
    DECL_ROP3(PSDPxax),
    DECL_ROP3(SPna),
    DECL_ROP3(DSna),
    DECL_ROP3(DPa),
    DECL_ROP3(PDxn),

    DECL_ROP3(DSxn),
    DECL_ROP3(PSDnox),
    DECL_ROP3(PDSona),
    DECL_ROP3(DSPDxox),
    DECL_ROP3(DPSDonox),
    DECL_ROP3(SPDSxax),

    DECL_ROP3(DPon),
    DECL_ROP3(DPna),
    DECL_ROP3(Pn),
    DECL_ROP3(PDna),
    DECL_ROP3(DPan),
    DECL_ROP3(DSan),
    DECL_ROP3(DSxn),
    DECL_ROP3(DPa),
    DECL_ROP3(D),
    DECL_ROP3(DPno),
    DECL_ROP3(SDno),
    DECL_ROP3(PDno),
    DECL_ROP3(DPo)
};

#define DECL_ROP2(x)   {GDI_R2_##x, #x}
QMap<uint8_t, QString> ROP2_TABLE = {
    DECL_ROP2(BLACK),
    DECL_ROP2(NOTMERGEPEN),
    DECL_ROP2(MASKNOTPEN),
    DECL_ROP2(NOTCOPYPEN),
    DECL_ROP2(MASKPENNOT),
    DECL_ROP2(NOT),
    DECL_ROP2(XORPEN),
    DECL_ROP2(NOTMASKPEN),
    DECL_ROP2(MASKPEN),
    DECL_ROP2(NOTXORPEN),
    DECL_ROP2(NOP),
    DECL_ROP2(MERGENOTPEN),
    DECL_ROP2(COPYPEN),
    DECL_ROP2(MERGEPENNOT),
    DECL_ROP2(MERGEPEN),
    DECL_ROP2(WHITE)
};
